# SwiftLint Configuration for LexiconFlow
#
# This configuration enforces code quality standards and prevents
# common issues like force unwraps and fatalError calls.
#
# Usage:
#   swiftlint                # Run linting
#   swiftlint --strict      # Fail on warnings
#   swiftlint --fix         # Auto-fix issues

# Disabled rules
disabled_rules:
  - trailing_whitespace      # Conflicts with editors

# Opt-in rules for additional safety
opt_in_rules:
  - force_unwrapping         # Detect force unwrap (!) usage
  - explicit_failure_calls   # Detect fatalError/preconditionFailure
  - actor_extraction         # Swift 6: Suggest actor extraction for mutable shared state
  - explicit_actor_exported  # Swift 6: Explicitly mark exported actors
  - redundant_self_in_closure  # Swift 6: Remove redundant self in closures
  - sorted_imports           # Enforce sorted imports

# Force unwrap should be error in production
force_unwrapping:
  severity: error

# Explicit failure calls (fatalError, preconditionFailure) should be warnings
explicit_failure_calls:
  severity: warning

# Excluded paths
excluded:
  - "**/*Tests.swift"        # Test code can use force unwrap for test doubles
  - "**/Pods/**"
  - "**/DerivedData/**"

# Line length
line_length:
  warning: 150
  error: 200
  ignores_function_declarations: true
  ignores_comments: true
  ignores_urls: true

# File length
file_length:
  warning: 500
  error: 1000
  ignore_comment_only_lines: true

# Function body length
function_body_length:
  warning: 60
  error: 100

# Type body length
type_body_length:
  warning: 350
  error: 500

# Identifier naming
identifier_name:
  min_length:
    warning: 2
  max_length:
    warning: 40
    error: 50
  excluded:
    - id                     # Common for UUID
    - x                      # Acceptable for coordinates
    - y
    - dx                     # Acceptable for deltas
    - dy

# Large tuples (should use structs instead)
large_tuple:
  warning: 3
  error: 4

# Nested function complexity
nesting:
  type_level:
    warning: 2
  function_level:
    warning: 3
    error: 5

# Custom rules to prevent common issues
custom_rules:
  # Detect force unwrap in production code
  no_force_unwrap:
    name: "No Force Unwrap"
    regex: '!\\s*(\\)|\\]|\\w)'
    match_kinds:
      - identifier
    message: "Avoid force unwrap. Use optional binding or nil coalescing instead."
    severity: error

  # Detect fatalError in production code
  no_fatal_error:
    name: "No Fatal Error"
    regex: 'fatalError\('
    message: "Avoid fatalError. Use graceful error handling instead."
    severity: warning

  # Detect TODO without issue reference
  todo_needs_issue:
    name: "TODO Needs Issue"
    regex: 'TODO:|FIXME:'
    message: "TODO/FIXME comments should reference an issue number"
    severity: warning

  # Swift 6: Prefer @MainActor or async/await over DispatchQueue
  prefer_asyncawait:
    name: "Prefer async/await"
    regex: 'DispatchQueue\.main\.async\s*\{'
    message: "Use @MainActor or async/await instead of DispatchQueue.main.async for Swift 6 concurrency"
    severity: warning

  # Swift 6: Prefer MainThread.isMainThread check in @MainActor contexts
  no_main_thread_precondition:
    name: "No MainThread.isMainThread Precondition"
    regex: 'precondition\(MainThread\.isMainThread\)'
    message: "Use @MainActor instead of MainThread.precondition for Swift 6"
    severity: warning

# Reporter configuration - GitHub Actions logging for CI, falls back to Xcode locally
reporter: "github-actions-logging"  # GitHub Actions-compatible output for CI
